services:
  php:
    container_name: lawetago-b2b-php
    build:
      context: docker/php-fpm/local
    user: root
    volumes:
      - ./:/var/www/app:rw,cached
      - socket:/var/run/
    secrets:
      - source: host_ssh_key
        target: /root/.ssh/id_rsa
    environment:
      PHP_IDE_CONFIG: "serverName=lawetago-b2b-php"
      SYMFONY_PHPUNIT_VERSION: "11.5"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "${NGINX_WEB_PORT:-91}:80"
    volumes:
      - ./:/var/www/app:cached
      - ./docker/nginx/local/default.conf:/etc/nginx/conf.d/default.conf
      - socket:/var/run/
    depends_on:
      - php

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "${POSTGRES_PORT:-55432}:5432"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

secrets:
  host_ssh_key:
    file: ${SSH_PRIVATE_KEY:-~/.ssh/id_rsa}

volumes:
  socket:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
